import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "@/src/ui/sonner";

import { QueryProvider } from "./components/query-provider";
import "@/src/app/globals.css";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jira Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${InterFont.variable} antialiased min-h-screen`}>
        <QueryProvider>
          <Toaster />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
